services:
  bot:
    build: .
    container_name: bot
    image: 4sfor/bot:latest
    depends_on:
      - nginx
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.27.0
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl